apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app:v10
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: todo
          image: abhishekf5/todo-app:v10
          ports:
            - containerPort: 8000
