apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app:v10
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: todo
<<<<<<< HEAD
          image: abhishekf5/todo-app:v10
=======
          image: 630210676530.dkr.ecr.us-east-1.amazonaws.com/ai-cicd:v10
>>>>>>> 778544b (update docker repo)
          ports:
            - containerPort: 8000
