apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: todo-app
      image: 630210676530.dkr.ecr.us-east-1.amazonaws.com/ai-cicd:v28
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred
