apiVersion: v1
kind: Pod
metadata:
  name: todo-app
spec:
  containers:
    - name: todo-app
      image: public.ecr.aws/m3j8h2a6/django-bot:v44
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: regcred
